### ISSUE TITLE
Error: Extension not working, showing CRASHED and STOPPED warning!

### ISSUE THREAD

**Issue by roshankhetpal** [Oxke/ulauncher-ytwl#2]
I've been trying to add youtube lazy watch extension for the last two days.

And get this error: While installing through add extension automatically.
It's showing a 'CRASHED' error.

When I added it manually by cloning the repo: It showed a 'STOPPED' error.

Here's the screenshot of error: 
![Screenshot from 2024-02-03 16-22-51](https://github.com/Oxke/ulauncher-ytwl/assets/112322609/07ce6382-e37a-41ec-927f-e7cb4e16ced1)

**Comment by Oxke** [comment]
Can you give me any additional information about your system?

**Comment by Oxke** [comment]
have you already run the setup script? if so, did it give any errors?

**Comment by roshankhetpal** [comment]
> Can you give me any additional information about your system?

Yeah sure, I'm currently on ubuntu 22.04, with gnome DE and wayland for windowing session.

**Comment by roshankhetpal** [comment]
> have you already run the setup script? if so, did it give any errors?

Firstly, when I tried to install YT lazy watch using a custom or manual proxy setting.

> Screenshot of my proxy settings
![Screenshot from 2024-02-04 09-35-29](https://github.com/Oxke/ulauncher-ytwl/assets/112322609/8629800c-449e-4566-949d-f562669357ef)

> And the extension adding error is here, with manual proxy setting->
![Screenshot from 2024-02-04 09-38-34](https://github.com/Oxke/ulauncher-ytwl/assets/112322609/6c8e629b-85f0-4041-9089-72329e078ffc)

Then I quickly figured this out and switched to my mobile hotspot with automatic proxy setting.

After changing my proxy settings from manual to automatic, the extension was added successfully. However, it showed errors indicating that it had `crashed` and `stopped`.

> You can see the error from this issue message -> #2

**Comment by Oxke** [comment]
Ok I changed a couple of things in the setup file. Now try this and check for errors (if so tell me at which point and report the error):

0. Probably it's not there, but check for the folder `~/.config/ulauncher/com.github.oxke.ulauncher-ytwl` and eventually remove it
1. Remove the extension and re-add it
2. Open a terminal and run the command `bash ~/.local/share/ulauncher/extensions/com.github.oxke.ulauncher-ytwl/setup`
3. Restart ulauncher and see if the extension is working (if so it will tell you to add the youtube data api key)

**Comment by RoshanKhetpal** [comment]
> Ok I changed a couple of things in the setup file. Now try this and check for errors (if so tell me at which point and report the error):
> 
> 0. Probably it's not there, but check for the folder `~/.config/ulauncher/com.github.oxke.ulauncher-ytwl` and eventually remove it
> 1. Remove the extension and re-add it
> 2. Open a terminal and run the command `bash ~/.local/share/ulauncher/extensions/com.github.oxke.ulauncher-ytwl/setup`
> 3. Restart ulauncher and see if the extension is working (if so it will tell you to add the youtube data api key)

Thank you so much, brother 🙏🏻.
Now, It's working fine after following your instructions.

![Screenshot from 2024-02-05 15-38-05](https://github.com/Oxke/ulauncher-ytwl/assets/112322609/0b35c13f-5d66-495d-b153-f87a16a9b2fa)

**Comment by roshankhetpal** [comment]
> Ok I changed a couple of things in the setup file. Now try this and check for errors (if so tell me at which point and report the error):
> 
> 0. Probably it's not there, but check for the folder `~/.config/ulauncher/com.github.oxke.ulauncher-ytwl` and eventually remove it
> 1. Remove the extension and re-add it
> 2. Open a terminal and run the command `bash ~/.local/share/ulauncher/extensions/com.github.oxke.ulauncher-ytwl/setup`
> 3. Restart ulauncher and see if the extension is working (if so it will tell you to add the youtube data api key)

Thank you so much, brother 🙏🏻.
Now, It's working fine after following your instructions.

I've added a YouTube API key and now everything is working perfectly!
![Screenshot from 2024-02-05 15-38-05](https://github.com/Oxke/ulauncher-ytwl/assets/112322609/0b35c13f-5d66-495d-b153-f87a16a9b2fa)

**Comment by Oxke** [comment]
Happy to help!
